[project]
name = "agente"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "crewai>=1.15.17",
    "paho-mqtt>=2.1.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
agente = "agente:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
